/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.proj.View;

import br.inatel.proj.Controller.ArquivoLogin;
import br.inatel.proj.Controller.ArquivoMesas;
import br.inatel.proj.Model.DungeonMaster;
import br.inatel.proj.Model.Mesa;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import static java.time.zone.ZoneRulesProvider.refresh;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author burns
 */
public class TelaMesas extends javax.swing.JFrame {

    private ArquivoMesas arquivo;
    private Mesa mesa = new Mesa();
    private ArrayList<Mesa> mesas = new ArrayList();
    private static DungeonMaster dmstatic = new DungeonMaster();//dungeon master dono dessa mesa
    private String userName;
    private String mesaName;

    private boolean tag = false;

    private DefaultListModel dlm = new DefaultListModel();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaMesas(DungeonMaster dm) { //construtor

        initComponents();
        this.setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btn_login);

        TelaMesas.dmstatic = dm;
        userName = dmstatic.getUserName();
        arquivo = new ArquivoMesas(userName);

        mesas = arquivo.ler();
        listar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        lbl_loginTitle = new javax.swing.JLabel();
        lbl_loginmesa = new javax.swing.JLabel();
        btn_novamesa = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_mesas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        lbl_loginTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_loginTitle.setText("Mesas");

        lbl_loginmesa.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_loginmesa.setText("Identificador: ");

        btn_novamesa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_novamesa.setText("Nova Mesa");
        btn_novamesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novamesaActionPerformed(evt);
            }
        });

        btn_login.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_login.setText("Entrar");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        list_mesas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        list_mesas.setModel(dlm);
        jScrollPane1.setViewportView(list_mesas);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_loginmesa)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lbl_loginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(btn_novamesa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(lbl_loginTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_loginmesa)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_login)
                    .addComponent(btn_novamesa))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novamesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novamesaActionPerformed
        criaMesa();
    }//GEN-LAST:event_btn_novamesaActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        selecionaMesa();
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMesas(dmstatic).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_novamesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_loginTitle;
    private javax.swing.JLabel lbl_loginmesa;
    private javax.swing.JList<String> list_mesas;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables

    private void criaMesa() {
        Mesa mesaAux = new Mesa();//cria uma mesa aux para ser inserida no arquivo
        String aux = JOptionPane.showInputDialog(rootPane, "entre com o nome da sua nova mes \n (você podera adicionar os personagens e npc's depois)");
        mesaAux.setNome(aux);
        mesaAux.setUserName(userName);

     /*   if (isUnique(mesaAux.getNome())) {*/
            // se nao existir cai aqui
            // salva os dados
            salvarDados(mesaAux);
       /* } else {
            // Caso esteja errado emite um Erro
            String msg = "Mesa já cadastrada!";
            String title = "Mesa já existe!";
            int msgType = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog(rootPane, msg, title, msgType);

        }*/
        listar();

    }

    private void selecionaMesa() {
        String mesa = list_mesas.getSelectedValue();//tring q recebe o valor selecionado da lista 
        findTable(mesa);
        /*apartir daqui o onjeto this.mesa ja tem a mesa selecionada pelo usuario 
        TODO chamar uma tela de controle mesa 
        fazer o mesmo processo de um item statico para elas , passando como parametro o onjeto this.mesa modificado nessa funçao
         */
        TelaControleMesa telaControle = new TelaControleMesa(userName, mesaName);
        telaControle.setVisible(true);
        this.dispose();
    }

    private boolean isUnique(String nomeDaMesa) {
        mesas = arquivo.ler();
        for (Mesa mesa1 : mesas) {
            if (mesa1.getNome().equals(nomeDaMesa)) {
                return false;
            }
        }
        return true;
    }

    private void salvarDados(Mesa mesa) {
        mesas.add(mesa);
        arquivo.salvarArquivo(mesas);

    }

    /**
     *
     * @param aux a string recebida pela jlist , seleciona o nome da mesa q eh
     * buscada o metodo usa a variavel global this.mesa para receber a mesa com
     * o nome selecionado
     */
    private void findTable(String aux) {
        boolean find = false;
        for (Mesa mesa1 : mesas) {
            if (mesa1.getNome().equals(aux)) {
                this.mesa = mesa1;
                find = true;

            }
        }
        if (!find) {
            System.out.println("em findtable nao encontramos a mesa no array mesas");
        }
    }

    private void listar() {
        dlm.clear();
        mesas = arquivo.ler();
        for (Mesa mesa1 : mesas) {
            dlm.addElement(mesa1.getNome());
        }
    }

}
