/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.proj.View;

import br.inatel.proj.Controller.ArquivoMesas;
import br.inatel.proj.Model.Chara;
import br.inatel.proj.Model.Mesa;
import br.inatel.proj.Model.Monstro;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author burns
 */
public class TelaMonstros extends javax.swing.JFrame {

    private ArquivoMesas arquivo = new ArquivoMesas();
    private Mesa mesa = new Mesa();
    private ArrayList<Mesa> mesas = new ArrayList();
    private ArrayList<Monstro> monstros = new ArrayList();
    private Monstro monstro = new Monstro();
    private DefaultListModel dlm = new DefaultListModel();
    private String userName;
    private String mesaName;
    private int index;

    /**
     * Creates new form TelaMonstros
     */
    public TelaMonstros() {
        initComponents();
        this.setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btn_showMonstro);
        this.userName = ArquivoMesas.autor;
        this.mesaName = ArquivoMesas.mesaName;
        this.mesas = arquivo.ler();
        findTable(ArquivoMesas.mesaName);

        this.index = this.mesas.indexOf(this.mesa);
        this.monstros = this.mesa.getMonstros();
        ArquivoMesas.monstro = this.monstro;

        listar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_showNotes = new javax.swing.JButton();
        lbl_personagens = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_monsters = new javax.swing.JList<>();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_showMonstro = new javax.swing.JButton();
        btn_AddMonstro = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_interface = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_showNotes.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_showNotes.setText("Notas");
        btn_showNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showNotesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_showNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 140, 30));

        lbl_personagens.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        lbl_personagens.setText("Monstros");
        jPanel1.add(lbl_personagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 228, -1));

        jList_monsters.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jList_monsters.setModel(dlm
        );
        jScrollPane1.setViewportView(jList_monsters);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 110));

        btn_editar.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        btn_excluir.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        btn_showMonstro.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_showMonstro.setText("Info");
        btn_showMonstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showMonstroActionPerformed(evt);
            }
        });
        jPanel1.add(btn_showMonstro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 140, 30));

        btn_AddMonstro.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_AddMonstro.setText("Adicionar Monstro");
        btn_AddMonstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddMonstroActionPerformed(evt);
            }
        });
        jPanel1.add(btn_AddMonstro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        btn_voltar.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        txta_interface.setColumns(20);
        txta_interface.setRows(5);
        jScrollPane2.setViewportView(txta_interface);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 224, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dungeons_and_Dragons_4th_Edition_Logo-600x400.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        editar();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        exluir();
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_showMonstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showMonstroActionPerformed
        showGeral();
    }//GEN-LAST:event_btn_showMonstroActionPerformed

    private void btn_AddMonstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddMonstroActionPerformed
        callAddMonstro();
    }//GEN-LAST:event_btn_AddMonstroActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        voltar();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_showNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showNotesActionPerformed
        showNotas();
    }//GEN-LAST:event_btn_showNotesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMonstros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMonstros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMonstros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMonstros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMonstros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddMonstro;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_showMonstro;
    private javax.swing.JButton btn_showNotes;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList_monsters;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_personagens;
    private javax.swing.JTextArea txta_interface;
    // End of variables declaration//GEN-END:variables

    private void editar() {
        String aux = jList_monsters.getSelectedValue();
        if (findMonster()) {
            if (aux != null) {
                ArquivoMesas.monstro = this.monstro;
                ArquivoMesas.isEdit = true;
                TelaAddMonstro tela = new TelaAddMonstro();
                tela.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "nao ha monstros ainda");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Monstro nao encontrado");
        }

    }

    private void exluir() {
        String aux = jList_monsters.getSelectedValue();

        if (aux != null) {
            for (Monstro monstro1 : this.monstros) {
                if (monstro1.getNome().equals(aux)) {
                    int indexAux = this.monstros.indexOf(monstro1);
                    String msg = "Deseja remover o monstro: " + monstro1.getNome() + "?";

                    int op = JOptionPane.showConfirmDialog(jScrollPane1, msg, "Excluir", JOptionPane.WARNING_MESSAGE);
                    if (op == 0) {
                        // OK: excluir o char
                        JOptionPane.showMessageDialog(jScrollPane1, "Monstro Removido com Sucesso!");
                        this.monstros.remove(indexAux);
                        this.mesa.setMonstros(monstros);
                        this.mesas.set(this.index, this.mesa);
                        arquivo.salvarArquivo(mesas);
                        listar();
                        index = 0;
                        break;
                    }

                }
            }

            listar();

        } else {
            JOptionPane.showMessageDialog(rootPane, "nao ha monstros ainda", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void showGeral() {
        if (findMonster()) {
            txta_interface.setText(this.monstro.showMonstro());
        } else {
            JOptionPane.showMessageDialog(rootPane, "monstro nao encontrado");
        }
    }

    private void voltar() {
        TelaControleMesa tela = new TelaControleMesa();
        tela.setVisible(true);
        this.dispose();
    }

    private void findTable(String aux) {
        boolean find = false;
        for (Mesa mesa1 : mesas) {
            if (mesa1.getNome().equals(aux)) {
                this.mesa = mesa1;
                find = true;

            }
        }
        if (!find) {
            System.out.println("wtf");
        }
    }

    private void listar() {
        dlm.clear();
        for (Monstro monstro1 : monstros) {
            dlm.addElement(monstro1.getNome());
        }
    }

    private void callAddMonstro() {
        TelaAddMonstro tela = new TelaAddMonstro();
        tela.setVisible(true);
        this.dispose();
    }

    private boolean findMonster() {
        String aux = jList_monsters.getSelectedValue();
        boolean find = false;
        for (Monstro monstro1 : monstros) {
            if (monstro1.getNome().equals(aux)) {
                this.monstro = monstro1;
                find = true;
                return find;

            }
        }
        if (!find) {
            System.out.println("find monstro chamado , nao encontrado monstro");
        }
        return find;
    }

    private void showNotas() {
if (findMonster()) {
            txta_interface.setText(this.monstro.getNotas());
        } else {
            JOptionPane.showMessageDialog(rootPane, "monstro nao encontrado");
        }    }
}
