/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.proj.View;

import br.inatel.proj.Controller.ArquivoMesas;
import br.inatel.proj.Model.Mesa;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.util.ArrayList;
import sun.security.jgss.spi.MechanismFactory;

/**
 *
 * @author burns
 */
public class TelaControleMesa extends javax.swing.JFrame {

    private ArquivoMesas arquivo = new ArquivoMesas();
    private Mesa mesa = new Mesa();//variavel mesa herdada da tela tela mesas
    private ArrayList<Mesa> mesas = new ArrayList();
    
    private String userName;
    private String mesaName;

    /**
     * Creates new form TelaControleMesa
     */
    public TelaControleMesa() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.userName = ArquivoMesas.autor;
        this.mesaName = ArquivoMesas.mesaName;
        
        mesas = arquivo.ler();
        findTable(ArquivoMesas.mesaName);

        lbl_charcounter1.setText(this.mesa.getCharacters().size() + "");
        lbl_monstercounter.setText(this.mesa.getMonstros().size() + "");
        lbl_npcounter.setText(this.mesa.getNpcs().size() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_mesaph = new javax.swing.JPanel();
        btn_personagens = new javax.swing.JButton();
        btn_monstros = new javax.swing.JButton();
        btn_npcs = new javax.swing.JButton();
        btn_combate = new javax.swing.JButton();
        lbl_npcounter = new javax.swing.JLabel();
        lbl_charcounter1 = new javax.swing.JLabel();
        lbl_monstercounter = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        lbl_imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_mesaph.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_personagens.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_personagens.setText("Personagens");
        btn_personagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personagensActionPerformed(evt);
            }
        });
        jp_mesaph.add(btn_personagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        btn_monstros.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_monstros.setText("Monstros");
        btn_monstros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_monstrosActionPerformed(evt);
            }
        });
        jp_mesaph.add(btn_monstros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        btn_npcs.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_npcs.setText("Npcs");
        btn_npcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_npcsActionPerformed(evt);
            }
        });
        jp_mesaph.add(btn_npcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        btn_combate.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_combate.setText("Combate");
        btn_combate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_combateActionPerformed(evt);
            }
        });
        jp_mesaph.add(btn_combate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        lbl_npcounter.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lbl_npcounter.setText("npc counter");
        jp_mesaph.add(lbl_npcounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 60, 30));

        lbl_charcounter1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lbl_charcounter1.setText("player counter");
        jp_mesaph.add(lbl_charcounter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 105, 70, 30));

        lbl_monstercounter.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lbl_monstercounter.setText("monster counter");
        jp_mesaph.add(lbl_monstercounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 90, 30));

        btn_voltar.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        jp_mesaph.add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        lbl_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dungeons_and_Dragons_4th_Edition_Logo-600x400.jpg"))); // NOI18N
        jp_mesaph.add(lbl_imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mesaph, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mesaph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_personagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personagensActionPerformed
        callChar();
    }//GEN-LAST:event_btn_personagensActionPerformed

    private void btn_npcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_npcsActionPerformed
        callNpc();
    }//GEN-LAST:event_btn_npcsActionPerformed

    private void btn_monstrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_monstrosActionPerformed
        callMonster();
    }//GEN-LAST:event_btn_monstrosActionPerformed

    private void btn_combateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_combateActionPerformed
        callCombat();
    }//GEN-LAST:event_btn_combateActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        voltat();
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaControleMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaControleMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaControleMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaControleMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaControleMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_combate;
    private javax.swing.JButton btn_monstros;
    private javax.swing.JButton btn_npcs;
    private javax.swing.JButton btn_personagens;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JPanel jp_mesaph;
    private javax.swing.JLabel lbl_charcounter1;
    private javax.swing.JLabel lbl_imagem;
    private javax.swing.JLabel lbl_monstercounter;
    private javax.swing.JLabel lbl_npcounter;
    // End of variables declaration//GEN-END:variables

    private void callChar() {
        TelaPersonagens telaChar = new TelaPersonagens();
        telaChar.setVisible(true);
        this.dispose();
    }

    private void callNpc() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void callMonster() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void callCombat() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void salvarDados(Mesa mesa) {
        mesas.add(mesa);
        System.out.println(arquivo.getAutor());
        for (Mesa mesa1 : mesas) {
            System.out.println(mesa1.getNome());
        }

        arquivo.salvarArquivo(mesas);

    }

    private void findTable(String aux) {
        boolean find = false;
        for (Mesa mesa1 : mesas) {
            if (mesa1.getNome().equals(aux)) {
                this.mesa = mesa1;
                find = true;

            }
        }
        if (!find) {
            System.out.println("wtf");
        }
    }

    private void voltat() {
        TelaMesas tela = new TelaMesas();
        tela.setVisible(true);
        this.dispose();
    }
}
