/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.proj.View;

import br.inatel.proj.Controller.ArquivoMesas;
import br.inatel.proj.Model.Mesa;
import br.inatel.proj.Model.Chara;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.xml.bind.annotation.XmlElement;

/**
 *
 * @author burns
 */
public class TelaPersonagens extends javax.swing.JFrame {

    private ArquivoMesas arquivo = new ArquivoMesas();
    private Mesa mesa = new Mesa();
    private ArrayList<Mesa> mesas = new ArrayList();
    private Chara achar = new Chara();
    private ArrayList<Chara> chars = new ArrayList();

    private DefaultListModel dlm = new DefaultListModel();

    private String userName;
    private String mesaName;
    private int index;

    /**
     * Creates new form TelaPersonagens
     */
    public TelaPersonagens() {
        initComponents();
        this.setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btn_showChar);

        this.userName = ArquivoMesas.autor;
        this.mesaName = ArquivoMesas.mesaName;

        this.mesas = arquivo.ler();
        findTable(ArquivoMesas.mesaName);
        
        this.index = this.mesas.indexOf(this.mesa);
        this.chars = this.mesa.getCharacters();
        ArquivoMesas.character = this.achar;

        //preenchendo a lista
        listar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_showNotes = new javax.swing.JButton();
        btn_Addchar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_chars = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_interface = new javax.swing.JTextArea();
        btn_showChar = new javax.swing.JButton();
        btn_showCombat = new javax.swing.JButton();
        btn_showAtributes = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        lbl_personagens = new javax.swing.JLabel();
        lbl_imgPersonagens = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_showNotes.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_showNotes.setText("Notas");
        btn_showNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showNotesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_showNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 140, 30));

        btn_Addchar.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_Addchar.setText("Adicionar Personagem");
        btn_Addchar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddcharActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Addchar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jList_chars.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jList_chars.setModel(dlm
        );
        jScrollPane1.setViewportView(jList_chars);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 110));

        txta_interface.setColumns(20);
        txta_interface.setRows(5);
        jScrollPane2.setViewportView(txta_interface);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 224, 280));

        btn_showChar.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_showChar.setText("Info Ceral");
        btn_showChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showCharActionPerformed(evt);
            }
        });
        jPanel1.add(btn_showChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 140, 30));

        btn_showCombat.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_showCombat.setText("Info Combate");
        btn_showCombat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showCombatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_showCombat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 140, 30));

        btn_showAtributes.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_showAtributes.setText("Info Atributos");
        btn_showAtributes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showAtributesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_showAtributes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 140, 30));

        btn_voltar.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        btn_editar.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        btn_excluir.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        lbl_personagens.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        lbl_personagens.setText("Personagens");
        jPanel1.add(lbl_personagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 228, -1));

        lbl_imgPersonagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dungeons_and_Dragons_4th_Edition_Logo-600x400.jpg"))); // NOI18N
        jPanel1.add(lbl_imgPersonagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_showAtributesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showAtributesActionPerformed
        showAtributos();
    }//GEN-LAST:event_btn_showAtributesActionPerformed

    private void btn_AddcharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddcharActionPerformed
        callAddChar();
    }//GEN-LAST:event_btn_AddcharActionPerformed

    private void btn_showCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showCharActionPerformed
        showGeral();
    }//GEN-LAST:event_btn_showCharActionPerformed

    private void btn_showCombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showCombatActionPerformed
        showCombate();
    }//GEN-LAST:event_btn_showCombatActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        voltar();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        editar();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        exluir();
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_showNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showNotesActionPerformed
        showNotas();
    }//GEN-LAST:event_btn_showNotesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPersonagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPersonagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPersonagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPersonagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPersonagens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Addchar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_showAtributes;
    private javax.swing.JButton btn_showChar;
    private javax.swing.JButton btn_showCombat;
    private javax.swing.JButton btn_showNotes;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JList<String> jList_chars;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_imgPersonagens;
    private javax.swing.JLabel lbl_personagens;
    private javax.swing.JTextArea txta_interface;
    // End of variables declaration//GEN-END:variables

    private void callAddChar() {
        TelaAddChar telaAddC = new TelaAddChar();
        telaAddC.setVisible(true);
        this.dispose();

    }

    private void findTable(String aux) {
        boolean find = false;
        for (Mesa mesa1 : mesas) {
            if (mesa1.getNome().equals(aux)) {
                this.mesa = mesa1;
                find = true;

            }
        }
        if (!find) {
            System.out.println("wtf");
        }
    }

    private void listar() { //lesta os personagens na jlist usando o dlm
        dlm.clear();
        for (Chara aChar : chars) {
            dlm.addElement(aChar.getNome());
        }
    }

    private boolean findChar() {
        String aux = jList_chars.getSelectedValue();
        boolean find = false;
        for (Chara aChar : chars) {
            if (aChar.getNome().equals(aux)) {
                this.achar = aChar;
                find = true;
                return find;

            }
        }
        if (!find) {
            System.out.println("findchar chamado , nao encontrado char");
        }
        return find;
    }

    private void showGeral() {
        if (findChar()) {
            txta_interface.setText(this.achar.showChar());
        } else {
            JOptionPane.showMessageDialog(rootPane, "char nao encontrado");
        }
    }

    private void showAtributos() {
        if (findChar()) {
            txta_interface.setText(this.achar.showAtributos());
        } else {
            JOptionPane.showMessageDialog(rootPane, "char nao encontrado");
        }
    }

    private void showCombate() {
        if (findChar()) {
            txta_interface.setText(this.achar.showCombat());
        } else {
            JOptionPane.showMessageDialog(rootPane, "char nao encontrado");
        }
    }

    private void voltar() {
        TelaControleMesa tela = new TelaControleMesa();
        tela.setVisible(true);
        this.dispose();
    }

    private void editar() {
        String aux = jList_chars.getSelectedValue();
        if (findChar()) {
            if (aux != null) {
                ArquivoMesas.character = this.achar;
                ArquivoMesas.isEdit = true;
                TelaAddChar tela = new TelaAddChar();
                tela.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "nao ha personagens ainda");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "char nao encontrado");
        }
    }

    private void exluir() {
        //findChar();
        String aux = jList_chars.getSelectedValue();

        if (aux != null) {
            for (Chara char1 : this.chars) {
                if (char1.getNome().equals(aux)) {
                    int indexAux = this.chars.indexOf(char1);
                    String msg = "Deseja remover o personagem: " + char1.getNome() + "?";

                    int op = JOptionPane.showConfirmDialog(jScrollPane1, msg, "Excluir", JOptionPane.WARNING_MESSAGE);
                    if (op == 0) {
                        // OK: excluir o char
                        JOptionPane.showMessageDialog(jScrollPane1, "personagem Removido com Sucesso!");
                        this.chars.remove(indexAux);
                        this.mesa.setCharacters(chars);
                        this.mesas.set(this.index, this.mesa);
                        arquivo.salvarArquivo(mesas);
                        listar();
                        index = 0;
                        break;
                    }

                }
            }

            listar();

        } else {
            JOptionPane.showMessageDialog(rootPane, "nao ha personagens ainda", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void showNotas() {
        if (findChar()) {
            txta_interface.setText(this.achar.getNotas());
        } else {
            JOptionPane.showMessageDialog(rootPane, "char nao encontrado");
        }
    }

}
